// Icon-class lookup table for giving accessible names to icon-only links/buttons.
// Keys are exact class tokens (matched longest-first). Pure module, unit-testable.

export const ICON_MAP = {
  'fa-twitter': 'Twitter', 'fa-x-twitter': 'X (Twitter)', 'fa-facebook': 'Facebook',
  'fa-facebook-f': 'Facebook', 'fa-instagram': 'Instagram', 'fa-linkedin': 'LinkedIn',
  'fa-linkedin-in': 'LinkedIn', 'fa-github': 'GitHub', 'fa-github-alt': 'GitHub',
  'fa-youtube': 'YouTube', 'fa-tiktok': 'TikTok', 'fa-pinterest': 'Pinterest',
  'fa-pinterest-p': 'Pinterest', 'fa-reddit': 'Reddit', 'fa-whatsapp': 'WhatsApp',
  'fa-telegram': 'Telegram', 'fa-mastodon': 'Mastodon', 'fa-discord': 'Discord',
  'fa-slack': 'Slack', 'fa-search': 'Search', 'fa-magnifying-glass': 'Search',
  'fa-envelope': 'Email', 'fa-envelope-o': 'Email', 'fa-envelope-open': 'Email',
  'fa-phone': 'Phone', 'fa-phone-alt': 'Phone', 'fa-mobile': 'Phone',
  'fa-user': 'User', 'fa-user-o': 'User', 'fa-users': 'Users', 'fa-group': 'Users',
  'fa-user-circle': 'User', 'fa-user-circle-o': 'User', 'fa-cart-arrow-down': 'Shopping cart',
  'fa-shopping-cart': 'Shopping cart', 'fa-shopping-bag': 'Shopping', 'fa-shopping-basket': 'Shopping',
  'fa-heart': 'Like', 'fa-heart-o': 'Like', 'fa-star': 'Star', 'fa-star-o': 'Star',
  'fa-menu': 'Menu', 'fa-bars': 'Menu', 'fa-navicon': 'Menu', 'fa-close': 'Close',
  'fa-times': 'Close', 'fa-xmark': 'Close', 'fa-x': 'Close', 'fa-edit': 'Edit',
  'fa-pencil': 'Edit', 'fa-pencil-alt': 'Edit', 'fa-trash': 'Delete', 'fa-trash-o': 'Delete',
  'fa-trash-alt': 'Delete', 'fa-download': 'Download', 'fa-upload': 'Upload',
  'fa-share': 'Share', 'fa-share-alt': 'Share', 'fa-cog': 'Settings', 'fa-cogs': 'Settings',
  'fa-gear': 'Settings', 'fa-wrench': 'Settings', 'fa-home': 'Home', 'fa-house': 'Home',
  'fa-bell': 'Notifications', 'fa-bell-o': 'Notifications', 'fa-info': 'Information',
  'fa-info-circle': 'Information', 'fa-question': 'Help', 'fa-question-circle': 'Help',
  'fa-arrow-left': 'Back', 'fa-chevron-left': 'Back', 'fa-arrow-right': 'Next',
  'fa-chevron-right': 'Next', 'fa-arrow-up': 'Up', 'fa-chevron-up': 'Up',
  'fa-arrow-down': 'Down', 'fa-chevron-down': 'Down', 'fa-play': 'Play',
  'fa-pause': 'Pause', 'fa-print': 'Print', 'fa-bookmark': 'Bookmark',
  'fa-bookmark-o': 'Bookmark', 'fa-calendar': 'Calendar', 'fa-clock': 'Clock',
  'fa-clock-o': 'Clock', 'fa-comments': 'Comments', 'fa-comment': 'Comment',
  'fa-thumbs-up': 'Thumbs up', 'fa-thumbs-o-up': 'Thumbs up', 'fa-thumbs-down': 'Thumbs down',
  'fa-thumbs-o-down': 'Thumbs down', 'fa-plus': 'Add', 'fa-minus': 'Remove',
  'fa-sun': 'Light mode', 'fa-moon': 'Dark mode',
  'fa-external-link': 'Opens in new tab', 'fa-external-link-alt': 'Opens in new tab',
  'fa-check': 'Confirm', 'fa-check-circle': 'Confirm', 'fa-check-circle-o': 'Confirm',
  'fa-lock': 'Locked', 'fa-unlock': 'Unlocked', 'fa-eye': 'Show', 'fa-eye-slash': 'Hide',
  'bi-twitter': 'Twitter', 'bi-facebook': 'Facebook', 'bi-instagram': 'Instagram',
  'bi-linkedin': 'LinkedIn', 'bi-github': 'GitHub', 'bi-youtube': 'YouTube',
  'bi-envelope': 'Email', 'bi-search': 'Search', 'bi-person': 'User', 'bi-person-circle': 'User',
  'bi-house': 'Home', 'bi-house-door': 'Home', 'bi-gear': 'Settings', 'bi-gear-fill': 'Settings',
  'bi-bell': 'Notifications', 'bi-cart': 'Shopping cart', 'bi-cart-fill': 'Shopping cart',
  'bi-bag': 'Shopping', 'bi-list': 'Menu', 'bi-list-ul': 'Menu', 'bi-x': 'Close',
  'bi-x-circle': 'Close', 'bi-x-square': 'Close', 'bi-trash': 'Delete', 'bi-pencil': 'Edit',
  'bi-download': 'Download', 'bi-share': 'Share', 'bi-heart': 'Like', 'bi-star': 'Star',
  'bi-arrow-left': 'Back', 'bi-arrow-right': 'Next', 'bi-chevron-left': 'Back',
  'bi-chevron-right': 'Next', 'bi-chevron-down': 'Expand', 'bi-chevron-up': 'Collapse',
  'bi-phone': 'Phone', 'bi-calendar': 'Calendar', 'bi-clock': 'Clock', 'bi-info-circle': 'Information',
  'bi-question-circle': 'Help', 'bi-play-btn': 'Play', 'bi-play-circle': 'Play',
  'bi-pause-btn': 'Pause', 'bi-print': 'Print', 'bi-bookmark': 'Bookmark',
  'bi-plus': 'Add', 'bi-dash': 'Remove', 'bi-check': 'Confirm', 'bi-check-circle': 'Confirm',
  'bi-lock': 'Locked', 'bi-eye': 'Show', 'bi-eye-slash': 'Hide', 'bi-sun': 'Light mode',
  'bi-moon': 'Dark mode', 'bi-grid': 'Grid', 'bi-grid-3x3-gap-fill': 'Grid',
  'bi-three-dots': 'More', 'bi-three-dots-vertical': 'More', 'bi-more': 'More',
  'glyphicon-search': 'Search', 'glyphicon-user': 'User', 'glyphicon-home': 'Home',
  'glyphicon-cog': 'Settings', 'glyphicon-envelope': 'Email', 'glyphicon-phone': 'Phone',
  'glyphicon-remove': 'Close', 'glyphicon-ok': 'Confirm', 'glyphicon-star': 'Star',
  'glyphicon-heart': 'Like', 'glyphicon-shopping-cart': 'Shopping cart',
  'glyphicon-trash': 'Delete', 'glyphicon-pencil': 'Edit', 'glyphicon-download': 'Download',
  'glyphicon-upload': 'Upload', 'glyphicon-share': 'Share', 'glyphicon-menu-hamburger': 'Menu',
  'glyphicon-chevron-left': 'Back', 'glyphicon-chevron-right': 'Next', 'glyphicon-play': 'Play',
  'glyphicon-pause': 'Pause', 'glyphicon-print': 'Print', 'glyphicon-calendar': 'Calendar',
  'glyphicon-time': 'Clock', 'glyphicon-comment': 'Comment', 'glyphicon-comments': 'Comments',
  'glyphicon-info-sign': 'Information', 'glyphicon-question-sign': 'Help',
  'glyphicon-plus': 'Add', 'glyphicon-minus': 'Remove', 'glyphicon-asterisk': 'Important',
  'glyphicon-eye-open': 'Show', 'glyphicon-eye-close': 'Hide', 'glyphicon-credit-card': 'Payment',
  'glyphicon-usd': 'Currency', 'glyphicon-euro': 'Currency', 'glyphicon-tags': 'Tags',
  'glyphicon-folder-open': 'Open folder', 'glyphicon-folder-close': 'Folder',
  'glyphicon-filter': 'Filter', 'glyphicon-sort': 'Sort', 'glyphicon-resize-full': 'Expand',
  'glyphicon-fullscreen': 'Fullscreen', 'glyphicon-log-out': 'Sign out', 'glyphicon-log-in': 'Sign in',
  'glyphicon-signal': 'Signal', 'glyphicon-warning-sign': 'Warning', 'glyphicon-alert': 'Alert',
  'glyphicon-bell': 'Notifications', 'glyphicon-gift': 'Gift', 'glyphicon-lock': 'Locked',
  'glyphicon-unlock': 'Unlocked', 'glyphicon-map-marker': 'Location', 'glyphicon-map-marker2': 'Location',
  'glyphicon-camera': 'Camera', 'glyphicon-film': 'Video', 'glyphicon-music': 'Music',
  'glyphicon-headphones': 'Audio', 'glyphicon-headset': 'Audio', 'glyphicon-king': 'Featured',
  'glyphicon-queen': 'Featured', 'glyphicon-glass': 'Drink', 'glyphicon-zoom-in': 'Zoom in',
  'glyphicon-zoom-out': 'Zoom out', 'glyphicon-fast-forward': 'Next', 'glyphicon-fast-backward': 'Back',
  'glyphicon-record': 'Record', 'glyphicon-stop': 'Stop', 'glyphicon-step-forward': 'Next',
  'glyphicon-step-backward': 'Back', 'glyphicon-flash': 'Lightning', 'glyphicon-wrench': 'Settings',
  'glyphicon-book': 'Book', 'glyphicon-duplicate': 'Duplicate', 'glyphicon-export': 'Export',
  'glyphicon-import': 'Import', 'glyphicon-list': 'List', 'glyphicon-th': 'Grid',
  'glyphicon-th-large': 'Grid', 'glyphicon-th-list': 'List', 'glyphicon-repeat': 'Repeat',
  'glyphicon-retweet': 'Share', 'glyphicon-refresh': 'Refresh',
  'icon-search': 'Search', 'icon-user': 'User', 'icon-menu': 'Menu', 'icon-home': 'Home',
  'icon-close': 'Close', 'icon-cart': 'Shopping cart', 'icon-phone': 'Phone',
  'icon-mail': 'Email', 'icon-gear': 'Settings', 'icon-settings': 'Settings',
  'icon-facebook': 'Facebook', 'icon-twitter': 'Twitter', 'icon-instagram': 'Instagram',
  'icon-linkedin': 'LinkedIn', 'icon-youtube': 'YouTube', 'icon-bars': 'Menu',
  'icon-navicon': 'Menu', 'icon-chevron-down': 'Expand', 'icon-chevron-up': 'Collapse',
  'icon-chevron-right': 'Next', 'icon-chevron-left': 'Back', 'icon-download': 'Download',
  'icon-upload': 'Upload', 'icon-share': 'Share', 'icon-heart': 'Like', 'icon-star': 'Star',
  'icon-trash': 'Delete', 'icon-edit': 'Edit', 'icon-pencil': 'Edit', 'icon-bell': 'Notifications',
  'icon-bell-o': 'Notifications', 'icon-info': 'Information', 'icon-info-circle': 'Information',
  'icon-question': 'Help', 'icon-question-circle': 'Help', 'icon-play': 'Play',
  'icon-pause': 'Pause', 'icon-print': 'Print', 'icon-calendar': 'Calendar',
  'icon-clock': 'Clock', 'icon-plus': 'Add', 'icon-minus': 'Remove', 'icon-comments': 'Comments',
  'icon-thumbs-up': 'Thumbs up', 'icon-check': 'Confirm', 'icon-check-circle': 'Confirm',
  'icon-lock': 'Locked', 'icon-eye': 'Show', 'icon-eye-slash': 'Hide', 'icon-sun': 'Light mode',
  'icon-moon': 'Dark mode', 'icon-external-link': 'Opens in new tab', 'icon-arrow-left': 'Back',
  'icon-arrow-right': 'Next', 'icon-arrow-up': 'Up', 'icon-arrow-down': 'Down',
  'material-icons-fill': 'Icon', 'material-icons-round': 'Icon', 'material-icons-outlined': 'Icon', 'search': 'Search', 'person': 'User', 'menu': 'Menu',
  'home': 'Home', 'settings': 'Settings', 'close': 'Close', 'shopping_cart': 'Shopping cart',
  'email': 'Email', 'phone': 'Phone', 'delete': 'Delete', 'edit': 'Edit',
  'arrow_back': 'Back', 'arrow_forward': 'Next', 'play_arrow': 'Play',
  'star': 'Star', 'favorite': 'Like', 'share': 'Share', 'more_vert': 'More',
  'account_circle': 'User', 'info': 'Information', 'warning': 'Warning',
  'help': 'Help', 'visibility': 'Show', 'visibility_off': 'Hide', 'lock': 'Locked',
  'notifications': 'Notifications', 'add': 'Add', 'remove': 'Remove', 'check': 'Confirm',
  'download': 'Download', 'upload': 'Upload', 'print': 'Print', 'calendar_today': 'Calendar',
  'schedule': 'Clock', 'comment': 'Comment', 'thumb_up': 'Thumbs up', 'icon-help': 'Help',
  'icon-phone-o': 'Phone', 'icon-search-o': 'Search', 'icon-envelope': 'Email', 'icon-envelope-o': 'Email',
};

const KEYS = Object.keys(ICON_MAP).sort((a, b) => b.length - a.length);

/**
 * Return a human-readable name for an icon class token, or null.
 * `tokens` is an array of class names (from element.classList).
 */
export function iconName(tokens) {
  for (const key of KEYS) {
    if (tokens.includes(key)) return ICON_MAP[key];
  }
  return null;
}